#!/usr/bin/env bash
# Package E2E: the .deb and .rpm install, work, and *refuse* where they should.
#
# The tarball gate next door proves the files work once placed. This one is
# about the metadata, which is the only thing a package adds and the only thing
# that can silently stop being true. Two halves, and the second matters more:
#
#   1. The package installs into a stock Postgres and the extension runs.
#   2. On a glibc older than the binary needs, the package manager REFUSES,
#      and places nothing. Without that, the dependency is decoration: the user
#      installs happily, edits shared_preload_libraries, and meets a postmaster
#      that will not start -- which looks like Axiom is broken rather than like
#      a download for the wrong distro.
#
# The refusal half is the reason this file exists. The .deb's floor is written
# by scripts/package-native from the ELF, and the .rpm's is generated by
# rpmbuild from the same ELF; either could regress to a number that is merely
# plausible, and nothing else would notice.
#
#   E2E_PACKAGE_MAJORS      majors to check (default: "16 17 18")
#   E2E_PACKAGE_RPM_MAJOR   major to run the RPM checks for (default: 17)
#   E2E_PACKAGE_RPM=0       skip the RPM half, which needs PGDG's yum repos
#
# Every container here runs with --rm and none is named, so there is nothing to
# leave behind and no cleanup trap to write. The artifacts in dist/ are build
# output and are meant to survive a failure, so they can be inspected.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAJORS="${E2E_PACKAGE_MAJORS:-16 17 18}"
RPM_MAJOR="${E2E_PACKAGE_RPM_MAJOR:-17}"
VERSION="$("$ROOT/scripts/version")"
# Package filenames spell a prerelease with a tilde, because rpm rejects a
# hyphen in a version and dpkg would misread one as the Debian revision -- see
# scripts/package-native. `axiom_version()` still reports the semver spelling,
# since that comes from CARGO_PKG_VERSION, so the two are asserted separately
# and must not be conflated.
PKG_VERSION="${VERSION//-/~}"
DIST="$ROOT/dist"
case "$(uname -m)" in
  x86_64) ARCH=amd64; RPM_ARCH=x86_64 ;;
  arm64|aarch64) ARCH=arm64; RPM_ARCH=aarch64 ;;
  *) echo "unsupported architecture $(uname -m)" >&2; exit 2 ;;
esac

log()  { printf '\n==> %s\n' "$*"; }
fail() { printf '\nE2E FAILED: %s\n' "$*" >&2; exit 1; }

# The RPM half needs PGDG's yum repo, which only publishes x86_64 and aarch64
# for EL9 -- both of which we have -- but the whole half is skippable so a
# network-restricted run can still gate the .deb.
RUN_RPM="${E2E_PACKAGE_RPM:-1}"

RETRY='retry() { n=0; until "$@"; do n=$((n+1)); [ "$n" -ge 3 ] && return 1; sleep $((n*5)); done; }; '

for pg in $MAJORS; do
  # Always repackaged, never reused: a package left in dist/ from before a
  # source edit would make this pass against code that is no longer there, and
  # the version only changes at release so the filename cannot show it.
  log "packaging pg${pg} (${ARCH})"
  "$ROOT/scripts/package-extension" "$pg" "$ARCH" >/dev/null \
    || fail "pg${pg}: could not build the packages"

  deb="$DIST/postgresql-${pg}-axiom_${PKG_VERSION}-1_${ARCH}.deb"
  [[ -f "$deb" ]] || fail "pg${pg}: no .deb at $deb"

  # The declared floor must be the floor the binary actually has. These are
  # different numbers whenever someone reads it off the build image instead of
  # the ELF, which is the mistake that put glibc 2.36 in the documentation.
  log "pg${pg}: the declared glibc floor matches the binary"
  declared="$(docker run --rm -v "$deb":/p.deb:ro debian:bookworm-slim \
    dpkg -I /p.deb 2>/dev/null | sed -n 's/.*libc6 (>= \([0-9.]*\)).*/\1/p')"
  # Extracted with objdump, deliberately not the readelf pipeline
  # scripts/glibc-floor uses. Checking a value against itself proves only that
  # the same code ran twice, so a flaw in that heuristic would make the
  # generator and this assertion agree on the same wrong number.
  actual="$(docker run --rm -v "$DIST":/d:ro debian:bookworm-slim bash -c "$RETRY"'
      retry apt-get -qq update >/dev/null 2>&1
      retry apt-get -qq install -y binutils dpkg-dev >/dev/null 2>&1
      cd /tmp && dpkg-deb -x /d/'"$(basename "$deb")"' x
      objdump -p "$(find x -name axiom.so)" \
        | awk "/GLIBC_/ { for (i=1;i<=NF;i++) if (\$i ~ /^GLIBC_/) { sub(/^GLIBC_/,\"\",\$i); print \$i } }" \
        | sort -uV | tail -1')" || true
  [[ -n "$declared" ]] || fail "pg${pg}: the .deb declares no libc6 floor at all"
  [[ "$declared" == "$actual" ]] \
    || fail "pg${pg}: .deb declares libc6 >= $declared but the binary needs $actual"
  echo "    declared $declared, binary needs $actual"

  # Install into upstream's image, which is Debian and already has the matching
  # postgresql-N package, so the dependency resolves the way a user's would.
  log "pg${pg}: the .deb installs and the extension runs"
  out="$(docker run --rm -v "$DIST":/d:ro "postgres:${pg}" bash -c "$RETRY"'
    set -e
    retry apt-get -qq update >/dev/null 2>&1
    retry apt-get install -y -qq /d/'"$(basename "$deb")"' >/dev/null 2>&1 || { echo "INSTALL-FAILED"; exit 1; }
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/initdb -D /tmp/data" >/dev/null 2>&1
    echo "shared_preload_libraries = '"'"'axiom'"'"'" >> /tmp/data/postgresql.conf
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/pg_ctl -D /tmp/data -l /tmp/pg.log -w start" >/dev/null \
      || { echo "POSTMASTER-FAILED"; tail -20 /tmp/pg.log; exit 1; }
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/psql -tAqc \"CREATE EXTENSION axiom;\"" >/dev/null
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/psql -tAqc \"SELECT axiom_version();\""
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/psql -tAqc \
      \"SELECT count(*) FROM pg_stat_activity WHERE backend_type ILIKE '"'"'%axiom%'"'"';\""
    # A package that cannot be removed is worse than a tarball, which at least
    # never claimed it could be.
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/pg_ctl -D /tmp/data -w stop" >/dev/null
    apt-get remove -y -qq postgresql-'"$pg"'-axiom >/dev/null 2>&1
    test ! -f /usr/lib/postgresql/'"$pg"'/lib/axiom.so && echo REMOVED
  ' 2>&1)" || fail "pg${pg}: .deb install path failed:
$out"
  grep -qx "$VERSION" <<<"$out" || fail "pg${pg}: axiom_version() did not report ${VERSION}:
$out"
  grep -q '^1$' <<<"$out" || fail "pg${pg}: the background worker is not running:
$out"
  grep -q '^REMOVED$' <<<"$out" || fail "pg${pg}: apt remove left axiom.so behind:
$out"
  echo "    version ${VERSION}, worker running, removed cleanly"

  # The half that actually justifies shipping a package: on a glibc below the
  # floor, apt must refuse and install nothing.
  #
  # Ubuntu 20.04 is glibc 2.31. It is used rather than Debian bullseye because
  # bullseye is EOL and deb.debian.org now 404s its security pool, so
  # installing anything there fails for reasons unrelated to this test.
  #
  # A stand-in postgresql-N is installed first, and that is the point of the
  # check rather than a detail. PGDG stopped publishing for focal, so without
  # it postgresql-N is simply missing, apt refuses over that as well, and the
  # assertions below hold for a package that is not actually protecting
  # anyone: `Depends: postgresql-N | libc6 (>= floor)` would still see apt cite
  # both unmet branches here, while on a real machine with Postgres installed
  # the first branch is satisfied and the thing installs onto glibc 2.31. With
  # the server dependency satisfied, glibc is the only objection left, so a
  # refusal can only have come from it.
  log "pg${pg}: the .deb refuses on a glibc below its floor"
  # Anchored on the left so it cannot be satisfied by some other package whose
  # name merely ends in libc6. apt always writes a space before the name.
  floor_re="(^| )libc6(:[a-z0-9-]+)? \\(>= ${declared//./\\.}\\)"
  # Native architecture, so apt is comparing like with like and the package is
  # not treated as foreign.
  out="$(docker run --rm --platform "linux/${ARCH}" -v "$DIST":/d:ro ubuntu:20.04 bash -c "$RETRY"'
    export DEBIAN_FRONTEND=noninteractive
    retry apt-get -qq update >/dev/null 2>&1
    # This system must really be below the floor, or the refusal proves
    # nothing. dpkg does the comparison, so it is apt policy deciding rather
    # than a string written here.
    have="$(dpkg-query -W -f="\${Version}" libc6)"
    dpkg --compare-versions "$have" ge "'"$declared"'" \
      || echo "BELOW-THE-FLOOR have=$have floor='"$declared"'"

    # A stand-in for the server package, so the only thing left to object to is
    # glibc. It carries no files; it exists to satisfy one dependency.
    mkdir -p /tmp/stand-in/DEBIAN
    printf "%s\n" \
      "Package: postgresql-'"$pg"'" \
      "Version: 99:0-stand-in" \
      "Architecture: $(dpkg --print-architecture)" \
      "Maintainer: axiom package gate <noreply@example.invalid>" \
      "Description: stand-in so the gate can attribute a refusal to glibc" \
      > /tmp/stand-in/DEBIAN/control
    dpkg-deb --root-owner-group --build /tmp/stand-in /tmp/stand-in.deb >/dev/null 2>&1
    dpkg -i /tmp/stand-in.deb >/dev/null 2>&1
    dpkg-query -W -f="\${Status}" postgresql-'"$pg"' 2>/dev/null | grep -q "install ok installed" \
      && echo SERVER-SATISFIED

    apt-get install -y /d/'"$(basename "$deb")"' >/tmp/o 2>&1 || true
    grep -qE "'"$floor_re"'" /tmp/o && echo CITED-THE-FLOOR
    grep -qE "(^| )postgresql-'"$pg"'(:[a-z0-9-]+)? " /tmp/o && echo ALSO-BLOCKED-BY-SERVER
    # Not a file check: /usr/lib/postgresql does not exist on a stock focal
    # image, so asserting the .so is absent would pass without apt having
    # decided anything. Whether dpkg registered the package is the real question.
    dpkg-query -W postgresql-'"$pg"'-axiom >/dev/null 2>&1 || echo NOT-INSTALLED
    # Carried out so a failure shows what apt actually said rather than only
    # which marker was missing.
    sed -n "/unmet dependencies/,/^E:/p" /tmp/o | sed "s/^/apt| /"
  ' 2>&1)" || true
  grep -q BELOW-THE-FLOOR <<<"$out" \
    || fail "pg${pg}: the test system is not below the declared floor of ${declared},
so its refusal would not show the constraint works:
$out"
  grep -q SERVER-SATISFIED <<<"$out" \
    || fail "pg${pg}: the stand-in postgresql-${pg} did not install, so a refusal here
cannot be attributed to glibc rather than to the missing server package:
$out"
  grep -q ALSO-BLOCKED-BY-SERVER <<<"$out" \
    && fail "pg${pg}: apt still objected to postgresql-${pg} despite the stand-in, so the
glibc constraint was not shown to be what refused:
$out"
  grep -q CITED-THE-FLOOR <<<"$out" \
    || fail "pg${pg}: with the server dependency satisfied and this system below the
floor, apt did not name 'libc6 (>= ${declared})' -- the dependency is not
load-bearing:
$out"
  grep -q NOT-INSTALLED <<<"$out" \
    || fail "pg${pg}: a refused install still registered the package with dpkg:
$out"
  echo "    server dependency satisfied, refused on libc6 alone, registered nothing"
done

if [[ "$RUN_RPM" == "1" ]]; then
  pg="$RPM_MAJOR"
  rpm_file="$(ls -1 "$DIST"/axiom_${pg}-${PKG_VERSION}-1*.${RPM_ARCH}.rpm 2>/dev/null | tail -1)" \
    || fail "no .rpm for pg${pg} ${RPM_ARCH} in dist/"
  [[ -n "$rpm_file" ]] || fail "no .rpm for pg${pg} ${RPM_ARCH} in dist/"
  base="$(basename "$rpm_file")"

  # rpmbuild generates the glibc requirement from the payload ELF. If that ever
  # stops happening the package installs anywhere and fails at postmaster
  # start, so assert the requirement is present rather than assuming rpmbuild
  # did its job.
  log "pg${pg}: the .rpm declares a generated glibc requirement"
  reqs="$(docker run --rm -v "$DIST":/d:ro rockylinux:9 rpm -qp --requires "/d/$base" 2>/dev/null)" || true
  grep -q 'libc\.so\.6(GLIBC_' <<<"$reqs" \
    || fail "pg${pg}: the .rpm declares no glibc symbol requirement:
$reqs"
  grep -q "postgresql${pg}-server" <<<"$reqs" \
    || fail "pg${pg}: the .rpm does not require postgresql${pg}-server:
$reqs"
  echo "    $(grep -c 'libc\.so\.6(GLIBC_' <<<"$reqs") glibc symbol requirements, requires postgresql${pg}-server"

  log "pg${pg}: the .rpm installs on EL9 and the extension runs"
  out="$(docker run --rm -v "$DIST":/d:ro rockylinux:9 bash -c "$RETRY"'
    set -e
    retry dnf install -y -q https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-'"$RPM_ARCH"'/pgdg-redhat-repo-latest.noarch.rpm >/dev/null 2>&1
    dnf -qy module disable postgresql >/dev/null 2>&1 || true
    retry dnf install -y -q /d/'"$base"' >/dev/null 2>&1 || { echo INSTALL-FAILED; exit 1; }
    su postgres -c "/usr/pgsql-'"$pg"'/bin/initdb -D /var/lib/pgsql/'"$pg"'/data" >/dev/null 2>&1
    echo "shared_preload_libraries = '"'"'axiom'"'"'" >> /var/lib/pgsql/'"$pg"'/data/postgresql.conf
    su postgres -c "/usr/pgsql-'"$pg"'/bin/pg_ctl -D /var/lib/pgsql/'"$pg"'/data -l /tmp/pg.log -w start" >/dev/null \
      || { echo POSTMASTER-FAILED; tail -20 /tmp/pg.log; exit 1; }
    su postgres -c "/usr/pgsql-'"$pg"'/bin/psql -tAqc \"CREATE EXTENSION axiom;\"" >/dev/null
    su postgres -c "/usr/pgsql-'"$pg"'/bin/psql -tAqc \"SELECT axiom_version();\""
  ' 2>&1)" || fail "pg${pg}: .rpm install path failed:
$out"
  grep -qx "$VERSION" <<<"$out" || fail "pg${pg}: axiom_version() did not report ${VERSION}:
$out"
  echo "    version ${VERSION} under PGDG postgresql${pg}-server"

  # EL8 is glibc 2.28, below the floor. dnf must refuse.
  #
  # PGDG's EL8 repository is enabled first for the same reason as bullseye
  # above: without it postgresql${pg}-server is missing too, dnf refuses for
  # two reasons, and the check would pass with no glibc requirement at all.
  log "pg${pg}: the .rpm refuses on EL8"
  out="$(docker run --rm -v "$DIST":/d:ro rockylinux:8 bash -c "$RETRY"'
    retry dnf install -y -q https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-'"$RPM_ARCH"'/pgdg-redhat-repo-latest.noarch.rpm >/dev/null 2>&1
    dnf -qy module disable postgresql >/dev/null 2>&1 || true
    retry dnf list --available postgresql'"$pg"'-server >/dev/null 2>&1 && echo SERVER-AVAILABLE
    dnf install -y /d/'"$base"' >/tmp/o 2>&1 || true
    grep -qi "nothing provides libc.so.6(GLIBC" /tmp/o && echo CITED-GLIBC
    grep -qi "nothing provides postgresql'"$pg"'-server" /tmp/o && echo ALSO-BLOCKED-BY-SERVER
    rpm -q axiom_'"$pg"' >/dev/null 2>&1 || echo NOT-INSTALLED
  ' 2>&1)" || true
  grep -q SERVER-AVAILABLE <<<"$out" \
    || fail "pg${pg}: postgresql${pg}-server is not available on EL8, so this check cannot
attribute the refusal to glibc. Fix the PGDG setup rather than trusting the result:
$out"
  grep -q ALSO-BLOCKED-BY-SERVER <<<"$out" \
    && fail "pg${pg}: dnf refused partly because postgresql${pg}-server was missing, so the
generated glibc requirement was not shown to be what refused:
$out"
  grep -q CITED-GLIBC <<<"$out" \
    || fail "pg${pg}: dnf did not refuse on EL8 citing glibc -- with the server package
available, that means the generated requirement is not load-bearing:
$out"
  grep -q NOT-INSTALLED <<<"$out" || fail "pg${pg}: a refused install still registered the package"
  echo "    refused, citing glibc, and installed nothing"
fi

printf '\nPACKAGE E2E PASSED\n'
