#!/usr/bin/env bash
# Package E2E: the .deb and .rpm install, work, and *refuse* where they should.
#
# The tarball gate next door proves the files work once placed. This one is
# about the metadata, which is the only thing a package adds and the only thing
# that can silently stop being true. Two halves, and the second matters more:
#
#   1. The package installs into a stock Postgres and the extension runs.
#   2. On a glibc older than the binary needs, the package manager REFUSES,
#      and places nothing. Without that, the dependency is decoration: the user
#      installs happily, edits shared_preload_libraries, and meets a postmaster
#      that will not start -- which looks like Axiom is broken rather than like
#      a download for the wrong distro.
#
# The refusal half is the reason this file exists. The .deb's floor is written
# by scripts/package-native from the ELF, and the .rpm's is generated by
# rpmbuild from the same ELF; either could regress to a number that is merely
# plausible, and nothing else would notice.
#
#   E2E_PACKAGE_MAJORS      majors to check (default: "16 17 18")
#   E2E_PACKAGE_RPM_MAJOR   major to run the RPM checks for (default: 17)
#   E2E_PACKAGE_KEEP=1      leave containers up on failure
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAJORS="${E2E_PACKAGE_MAJORS:-16 17 18}"
RPM_MAJOR="${E2E_PACKAGE_RPM_MAJOR:-17}"
VERSION="$("$ROOT/scripts/version")"
DIST="$ROOT/dist"
case "$(uname -m)" in
  x86_64) ARCH=amd64; RPM_ARCH=x86_64 ;;
  arm64|aarch64) ARCH=arm64; RPM_ARCH=aarch64 ;;
  *) echo "unsupported architecture $(uname -m)" >&2; exit 2 ;;
esac

log()  { printf '\n==> %s\n' "$*"; }
fail() { printf '\nE2E FAILED: %s\n' "$*" >&2; exit 1; }

# The RPM half needs PGDG's yum repo, which only publishes x86_64 and aarch64
# for EL9 -- both of which we have -- but the whole half is skippable so a
# network-restricted run can still gate the .deb.
RUN_RPM="${E2E_PACKAGE_RPM:-1}"

for pg in $MAJORS; do
  # Always repackaged, never reused: a package left in dist/ from before a
  # source edit would make this pass against code that is no longer there, and
  # the version only changes at release so the filename cannot show it.
  log "packaging pg${pg} (${ARCH})"
  "$ROOT/scripts/package-extension" "$pg" "$ARCH" >/dev/null \
    || fail "pg${pg}: could not build the packages"

  deb="$DIST/postgresql-${pg}-axiom_${VERSION}-1_${ARCH}.deb"
  [[ -f "$deb" ]] || fail "pg${pg}: no .deb at $deb"

  # The declared floor must be the floor the binary actually has. These are
  # different numbers whenever someone reads it off the build image instead of
  # the ELF, which is the mistake that put glibc 2.36 in the documentation.
  log "pg${pg}: the declared glibc floor matches the binary"
  declared="$(docker run --rm -v "$deb":/p.deb:ro debian:bookworm-slim \
    dpkg -I /p.deb 2>/dev/null | sed -n 's/.*libc6 (>= \([0-9.]*\)).*/\1/p')"
  # Extracted with objdump, deliberately not the readelf pipeline
  # scripts/glibc-floor uses. Checking a value against itself proves only that
  # the same code ran twice, so a flaw in that heuristic would make the
  # generator and this assertion agree on the same wrong number.
  actual="$(docker run --rm -v "$DIST":/d:ro debian:bookworm-slim bash -c '
      apt-get -qq update >/dev/null 2>&1 && apt-get -qq install -y binutils dpkg-dev >/dev/null 2>&1
      cd /tmp && dpkg-deb -x /d/'"$(basename "$deb")"' x
      objdump -p "$(find x -name axiom.so)" \
        | awk "/GLIBC_/ { for (i=1;i<=NF;i++) if (\$i ~ /^GLIBC_/) { sub(/^GLIBC_/,\"\",\$i); print \$i } }" \
        | sort -uV | tail -1')"
  [[ -n "$declared" ]] || fail "pg${pg}: the .deb declares no libc6 floor at all"
  [[ "$declared" == "$actual" ]] \
    || fail "pg${pg}: .deb declares libc6 >= $declared but the binary needs $actual"
  echo "    declared $declared, binary needs $actual"

  # Install into upstream's image, which is Debian and already has the matching
  # postgresql-N package, so the dependency resolves the way a user's would.
  log "pg${pg}: the .deb installs and the extension runs"
  out="$(docker run --rm -v "$DIST":/d:ro "postgres:${pg}" bash -c '
    set -e
    apt-get -qq update >/dev/null 2>&1
    apt-get install -y -qq /d/'"$(basename "$deb")"' >/dev/null 2>&1 || { echo "INSTALL-FAILED"; exit 1; }
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/initdb -D /tmp/data" >/dev/null 2>&1
    echo "shared_preload_libraries = '"'"'axiom'"'"'" >> /tmp/data/postgresql.conf
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/pg_ctl -D /tmp/data -l /tmp/pg.log -w start" >/dev/null \
      || { echo "POSTMASTER-FAILED"; tail -20 /tmp/pg.log; exit 1; }
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/psql -tAqc \"CREATE EXTENSION axiom;\"" >/dev/null
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/psql -tAqc \"SELECT axiom_version();\""
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/psql -tAqc \
      \"SELECT count(*) FROM pg_stat_activity WHERE backend_type ILIKE '"'"'%axiom%'"'"';\""
    # A package that cannot be removed is worse than a tarball, which at least
    # never claimed it could be.
    su postgres -c "/usr/lib/postgresql/'"$pg"'/bin/pg_ctl -D /tmp/data -w stop" >/dev/null
    apt-get remove -y -qq postgresql-'"$pg"'-axiom >/dev/null 2>&1
    test ! -f /usr/lib/postgresql/'"$pg"'/lib/axiom.so && echo REMOVED
  ' 2>&1)" || fail "pg${pg}: .deb install path failed:
$out"
  grep -qx "$VERSION" <<<"$out" || fail "pg${pg}: axiom_version() did not report ${VERSION}:
$out"
  grep -q '^1$' <<<"$out" || fail "pg${pg}: the background worker is not running:
$out"
  grep -q '^REMOVED$' <<<"$out" || fail "pg${pg}: apt remove left axiom.so behind:
$out"
  echo "    version ${VERSION}, worker running, removed cleanly"

  # The half that actually justifies shipping a package. bullseye is glibc
  # 2.31, below the floor, so apt must refuse and place nothing.
  #
  # PGDG's bullseye repository is added first, and that is the whole point of
  # the check rather than a detail. Without it `postgresql-${pg}` does not
  # exist on bullseye either, apt refuses for two reasons at once, and the
  # test would pass even if the libc6 constraint were absent -- proving only
  # that bullseye has no modern Postgres, which is not what is being claimed.
  # With the server package installable, glibc is the *only* thing left to
  # refuse, so a pass means the constraint carried the refusal on its own.
  log "pg${pg}: the .deb refuses on a glibc below its floor"
  out="$(docker run --rm -v "$DIST":/d:ro debian:bullseye-slim bash -c '
    set -e
    apt-get -qq update >/dev/null 2>&1
    apt-get -qq install -y curl ca-certificates gnupg >/dev/null 2>&1
    install -d /usr/share/postgresql-common/pgdg
    curl -fsSL -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc \
      https://www.postgresql.org/media/keys/ACCC4CF8.asc
    echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list
    apt-get -qq update >/dev/null 2>&1
    # If the server package is not actually installable the rest proves
    # nothing, so say so rather than passing.
    apt-cache policy postgresql-'"$pg"' | grep -qE "Candidate: [0-9]" && echo SERVER-AVAILABLE
    apt-get install -y /d/'"$(basename "$deb")"' >/tmp/o 2>&1 || true
    grep -qF "libc6 (>= '"$declared"')" /tmp/o && echo CITED-THE-FLOOR
    grep -q "postgresql-'"$pg"' but it is not installable" /tmp/o && echo ALSO-BLOCKED-BY-SERVER
    test ! -f /usr/lib/postgresql/'"$pg"'/lib/axiom.so && echo PLACED-NOTHING
  ' 2>&1)"
  grep -q SERVER-AVAILABLE <<<"$out" \
    || fail "pg${pg}: postgresql-${pg} is not installable on bullseye, so this check cannot
attribute the refusal to glibc. Fix the PGDG setup rather than trusting the result:
$out"
  grep -q ALSO-BLOCKED-BY-SERVER <<<"$out" \
    && fail "pg${pg}: apt refused partly because postgresql-${pg} was missing, so the
glibc constraint was not shown to be what refused:
$out"
  grep -q CITED-THE-FLOOR <<<"$out" \
    || fail "pg${pg}: apt did not refuse citing 'libc6 (>= ${declared})' -- with the server
package available, that means the floor is not load-bearing:
$out"
  grep -q PLACED-NOTHING <<<"$out" || fail "pg${pg}: a refused install still placed axiom.so"
  echo "    refused, citing libc6, and placed nothing"
done

if [[ "$RUN_RPM" == "1" ]]; then
  pg="$RPM_MAJOR"
  rpm_file="$(ls -1 "$DIST"/axiom_${pg}-${VERSION}-1*.${RPM_ARCH}.rpm 2>/dev/null | tail -1)" \
    || fail "no .rpm for pg${pg} ${RPM_ARCH} in dist/"
  [[ -n "$rpm_file" ]] || fail "no .rpm for pg${pg} ${RPM_ARCH} in dist/"
  base="$(basename "$rpm_file")"

  # rpmbuild generates the glibc requirement from the payload ELF. If that ever
  # stops happening the package installs anywhere and fails at postmaster
  # start, so assert the requirement is present rather than assuming rpmbuild
  # did its job.
  log "pg${pg}: the .rpm declares a generated glibc requirement"
  reqs="$(docker run --rm -v "$DIST":/d:ro rockylinux:9 rpm -qp --requires "/d/$base" 2>/dev/null)"
  grep -q 'libc\.so\.6(GLIBC_' <<<"$reqs" \
    || fail "pg${pg}: the .rpm declares no glibc symbol requirement:
$reqs"
  grep -q "postgresql${pg}-server" <<<"$reqs" \
    || fail "pg${pg}: the .rpm does not require postgresql${pg}-server:
$reqs"
  echo "    $(grep -c 'libc\.so\.6(GLIBC_' <<<"$reqs") glibc symbol requirements, requires postgresql${pg}-server"

  log "pg${pg}: the .rpm installs on EL9 and the extension runs"
  out="$(docker run --rm -v "$DIST":/d:ro rockylinux:9 bash -c '
    set -e
    dnf install -y -q https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-'"$RPM_ARCH"'/pgdg-redhat-repo-latest.noarch.rpm >/dev/null 2>&1
    dnf -qy module disable postgresql >/dev/null 2>&1 || true
    dnf install -y -q /d/'"$base"' >/dev/null 2>&1 || { echo INSTALL-FAILED; exit 1; }
    su postgres -c "/usr/pgsql-'"$pg"'/bin/initdb -D /var/lib/pgsql/'"$pg"'/data" >/dev/null 2>&1
    echo "shared_preload_libraries = '"'"'axiom'"'"'" >> /var/lib/pgsql/'"$pg"'/data/postgresql.conf
    su postgres -c "/usr/pgsql-'"$pg"'/bin/pg_ctl -D /var/lib/pgsql/'"$pg"'/data -l /tmp/pg.log -w start" >/dev/null \
      || { echo POSTMASTER-FAILED; tail -20 /tmp/pg.log; exit 1; }
    su postgres -c "/usr/pgsql-'"$pg"'/bin/psql -tAqc \"CREATE EXTENSION axiom;\"" >/dev/null
    su postgres -c "/usr/pgsql-'"$pg"'/bin/psql -tAqc \"SELECT axiom_version();\""
  ' 2>&1)" || fail "pg${pg}: .rpm install path failed:
$out"
  grep -qx "$VERSION" <<<"$out" || fail "pg${pg}: axiom_version() did not report ${VERSION}:
$out"
  echo "    version ${VERSION} under PGDG postgresql${pg}-server"

  # EL8 is glibc 2.28, below the floor. dnf must refuse.
  #
  # PGDG's EL8 repository is enabled first for the same reason as bullseye
  # above: without it postgresql${pg}-server is missing too, dnf refuses for
  # two reasons, and the check would pass with no glibc requirement at all.
  log "pg${pg}: the .rpm refuses on EL8"
  out="$(docker run --rm -v "$DIST":/d:ro rockylinux:8 bash -c '
    dnf install -y -q https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-'"$RPM_ARCH"'/pgdg-redhat-repo-latest.noarch.rpm >/dev/null 2>&1
    dnf -qy module disable postgresql >/dev/null 2>&1 || true
    dnf list --available postgresql'"$pg"'-server >/dev/null 2>&1 && echo SERVER-AVAILABLE
    dnf install -y /d/'"$base"' >/tmp/o 2>&1 || true
    grep -qi "nothing provides libc.so.6(GLIBC" /tmp/o && echo CITED-GLIBC
    grep -qi "nothing provides postgresql'"$pg"'-server" /tmp/o && echo ALSO-BLOCKED-BY-SERVER
    rpm -q axiom_'"$pg"' >/dev/null 2>&1 || echo NOT-INSTALLED
  ' 2>&1)"
  grep -q SERVER-AVAILABLE <<<"$out" \
    || fail "pg${pg}: postgresql${pg}-server is not available on EL8, so this check cannot
attribute the refusal to glibc. Fix the PGDG setup rather than trusting the result:
$out"
  grep -q ALSO-BLOCKED-BY-SERVER <<<"$out" \
    && fail "pg${pg}: dnf refused partly because postgresql${pg}-server was missing, so the
generated glibc requirement was not shown to be what refused:
$out"
  grep -q CITED-GLIBC <<<"$out" \
    || fail "pg${pg}: dnf did not refuse on EL8 citing glibc -- with the server package
available, that means the generated requirement is not load-bearing:
$out"
  grep -q NOT-INSTALLED <<<"$out" || fail "pg${pg}: a refused install still registered the package"
  echo "    refused, citing glibc, and installed nothing"
fi

printf '\nPACKAGE E2E PASSED\n'
