// Command docsgen writes the generated half of Axiom's documentation.
//
// It covers exactly the material where code is the sole source of truth
// (docs/PLAN.md Phase 6 Part 2): the gRPC API, the gateway's command-line
// flags, the FDW's server and foreign-table options, and the column projection
// rules. Architecture, runbooks and guides are written by people and are not
// produced here.
//
// The anti-drift guarantee is mechanical, not editorial: `make docs-generate`
// rewrites docs/generated/ and CI fails if that leaves the tree dirty, the
// same shape the repository already uses for `make proto-check`. Nothing here
// invents prose. Every sentence on a generated page is a comment or a literal
// lifted from the source it documents, so the way to edit a generated page is
// to edit the code it came from.
//
//	go run ./cmd/docsgen -root ../ -out ../docs/generated
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dhilipkumars/axiom/gateway/internal/cli"
	"github.com/dhilipkumars/axiom/gateway/internal/k8s"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docsgen:", err)
		os.Exit(1)
	}
}

func run() error {
	root := flag.String("root", "..", "repository root")
	out := flag.String("out", "../docs/generated", "directory to write the generated pages into")
	flag.Parse()

	if err := os.MkdirAll(*out, 0o755); err != nil {
		return err
	}

	pages := []struct {
		file string
		gen  func(string) ([]byte, error)
	}{
		{"api.md", genAPI},
		{"gateway-flags.md", genFlags},
		{"fdw-options.md", genOptions},
		{"columns.md", genColumns},
	}
	for _, p := range pages {
		b, err := p.gen(*root)
		if err != nil {
			return fmt.Errorf("%s: %w", p.file, err)
		}
		path := filepath.Join(*out, p.file)
		if err := os.WriteFile(path, b, 0o644); err != nil {
			return err
		}
		fmt.Println("wrote", path)
	}
	return nil
}

// header is the banner every generated page carries. It names the source so a
// reader who wants to change the page knows where to go, and states the rule
// that makes editing the page itself pointless.
func header(w *bytes.Buffer, title string, sources ...string) {
	fmt.Fprintf(w, "<!-- Generated by `make docs-generate` from %s. Do not edit. -->\n\n",
		strings.Join(sources, ", "))
	fmt.Fprintf(w, "# %s\n\n", title)
	fmt.Fprintf(w, "_Generated from %s. Edit %s and run `make docs-generate`; "+
		"CI fails on an uncommitted difference._\n\n",
		codeList(sources), map[bool]string{true: "that file", false: "those files"}[len(sources) == 1])
}

// para joins a comment block into one markdown paragraph per blank-line group,
// so the source's own paragraphing survives.
func para(lines []string) string {
	var paras []string
	var cur []string
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			if len(cur) > 0 {
				paras = append(paras, strings.Join(cur, " "))
				cur = nil
			}
			continue
		}
		cur = append(cur, l)
	}
	if len(cur) > 0 {
		paras = append(paras, strings.Join(cur, " "))
	}
	return strings.Join(paras, "\n\n")
}

// --- the gRPC API -----------------------------------------------------------

func genAPI(root string) ([]byte, error) {
	src := filepath.Join("proto", "axiom", "v1", "axiom.proto")
	pf, err := parseProto(filepath.Join(root, src))
	if err != nil {
		return nil, err
	}
	w := &bytes.Buffer{}
	header(w, "gRPC API reference", src)

	if d := para(pf.FileDoc); d != "" {
		fmt.Fprintf(w, "%s\n\n", d)
	}
	fmt.Fprintf(w, "Package `%s`. All calls are TLS-only; credentials are never message fields.\n\n",
		pf.Package)

	fmt.Fprintf(w, "## Service `%s`\n\n", pf.Service)
	if d := para(pf.SvcDoc); d != "" {
		fmt.Fprintf(w, "%s\n\n", d)
	}

	fmt.Fprintf(w, "| RPC | Request | Response |\n|---|---|---|\n")
	for _, r := range pf.RPCs {
		resp := "`" + r.Resp + "`"
		if r.ServerStream {
			resp = "stream of " + resp
		}
		fmt.Fprintf(w, "| [`%s`](#%s) | `%s` | %s |\n",
			r.Name, strings.ToLower(r.Name), r.Req, resp)
	}
	w.WriteString("\n")

	for _, r := range pf.RPCs {
		fmt.Fprintf(w, "### %s\n\n", r.Name)
		stream := ""
		if r.ServerStream {
			stream = "stream "
		}
		fmt.Fprintf(w, "```proto\nrpc %s(%s) returns (%s%s);\n```\n\n", r.Name, r.Req, stream, r.Resp)
		if d := para(r.Doc); d != "" {
			fmt.Fprintf(w, "%s\n\n", d)
		}
	}

	w.WriteString("## Messages\n\n")
	msgs := append([]messageDef(nil), pf.Messages...)
	sort.Slice(msgs, func(i, j int) bool { return msgs[i].Name < msgs[j].Name })
	for _, m := range msgs {
		fmt.Fprintf(w, "### %s\n\n", m.Name)
		if d := para(m.Doc); d != "" {
			fmt.Fprintf(w, "%s\n\n", d)
		}
		if len(m.Fields) == 0 {
			w.WriteString("_No fields._\n\n")
			continue
		}
		fmt.Fprintf(w, "| Field | Type | Description |\n|---|---|---|\n")
		for _, f := range m.Fields {
			typ := "`" + f.Type + "`"
			if f.Repeated {
				typ = "repeated " + typ
			}
			fmt.Fprintf(w, "| `%s` | %s | %s |\n", f.Name, typ, cell(para(f.Doc)))
		}
		w.WriteString("\n")
	}
	return w.Bytes(), nil
}

// cell makes a paragraph safe inside a markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	if s == "" {
		return "—"
	}
	return s
}

// --- gateway flags ----------------------------------------------------------

func genFlags(root string) ([]byte, error) {
	fs := flag.NewFlagSet("gateway", flag.ContinueOnError)
	cli.Register(fs, k8s.DefaultServe)

	w := &bytes.Buffer{}
	header(w, "Gateway command-line flags", filepath.Join("gateway", "internal", "cli", "flags.go"))
	w.WriteString("The gateway takes all of its configuration from flags. " +
		"It reads no environment variables and no configuration file, so what a " +
		"running gateway is doing is visible in its Pod spec or its command line.\n\n")

	fmt.Fprintf(w, "| Flag | Default | Description |\n|---|---|---|\n")
	var rows []string
	fs.VisitAll(func(f *flag.Flag) {
		def := f.DefValue
		switch def {
		case "":
			def = "_(none)_"
		default:
			def = "`" + def + "`"
		}
		// flag.UnquoteUsage strips the backquoted value-name convention out of
		// the usage string, the same way `-help` renders it.
		_, usage := flag.UnquoteUsage(f)
		rows = append(rows, fmt.Sprintf("| `-%s` | %s | %s |\n", f.Name, def, cell(usage)))
	})
	sort.Strings(rows)
	for _, r := range rows {
		w.WriteString(r)
	}
	w.WriteString("\nBoth `-tls-cert` and `-tls-key` are required: the gateway has no " +
		"plaintext mode, so it refuses to start without a server keypair.\n")
	return w.Bytes(), nil
}

// --- FDW options ------------------------------------------------------------

func genOptions(root string) ([]byte, error) {
	// Two files, because IMPORT FOREIGN SCHEMA's options live with the import
	// code that consumes them rather than with the validator's.
	srcs := []string{
		filepath.Join("extension", "src", "options.rs"),
		filepath.Join("extension", "src", "import.rs"),
	}
	var cats []fdwCatalog
	for _, src := range srcs {
		c, err := parseFDWOptions(filepath.Join(root, src))
		if err != nil {
			return nil, err
		}
		cats = append(cats, c...)
	}

	w := &bytes.Buffer{}
	header(w, "Foreign data wrapper options", srcs...)
	w.WriteString("These are every option the validator accepts. An option not " +
		"listed for a statement is rejected at DDL time, naming the statement and " +
		"the offending option, rather than being ignored.\n\n")

	for _, c := range cats {
		fmt.Fprintf(w, "## `%s`\n\n", c.Title)
		if c.Doc != "" {
			fmt.Fprintf(w, "%s\n\n", c.Doc)
		}
		fmt.Fprintf(w, "| Option | Required | Default | Meaning |\n|---|---|---|---|\n")
		for _, o := range c.Options {
			req, def := "no", "_(none)_"
			if o.Required {
				req = "**yes**"
			}
			if o.Default != "" {
				def = "`" + o.Default + "`"
			}
			fmt.Fprintf(w, "| `%s` | %s | %s | %s |\n", o.Name, req, def, cell(o.Summary))
		}
		w.WriteString("\n")
	}
	w.WriteString("## `CREATE FOREIGN DATA WRAPPER` and `CREATE USER MAPPING`\n\n" +
		"Neither accepts any option today, and both reject any that is given. " +
		"The wrapper carries no configuration of its own, and per-caller " +
		"credentials on a user mapping arrive in Phase 7 (see `docs/AUTH.md`).\n")
	return w.Bytes(), nil
}

// --- column projection ------------------------------------------------------

func genColumns(root string) ([]byte, error) {
	src := filepath.Join("gateway", "internal", "k8s", "schema.go")
	w := &bytes.Buffer{}
	header(w, "Foreign table columns", src)
	w.WriteString("`IMPORT FOREIGN SCHEMA` derives a table's shape from the kind's " +
		"identity and its OpenAPI schema. This page lists what that produces. " +
		"The extension holds the matching projection rules in " +
		"`extension/src/schema.rs`, and unit tests on both sides assert the two " +
		"agree.\n\n")

	w.WriteString("## Types\n\n" +
		"Columns are `text` or `jsonb` and nothing else. An OpenAPI schema " +
		"frequently does not constrain a field tightly enough to justify a " +
		"numeric or timestamp column, and guessing wrong turns a queryable table " +
		"into a cast-error minefield. Promoted scalars are `text`, so " +
		"`replicas::int` is the caller's explicit choice and an absent field is " +
		"NULL rather than zero.\n\n")

	w.WriteString("## Universal columns\n\n" +
		"Every kind gets these, whatever its schema, in this order. " +
		"`api_version`, `kind` and `metadata` are the only three fields present " +
		"on every Kubernetes object, which is what makes them the keys a query " +
		"spanning kinds can use. `namespace` is omitted for cluster-scoped " +
		"kinds.\n\n")
	colTable(w, k8s.UniversalColumns())

	w.WriteString("\n## Promoted columns\n\n" +
		"Hand-mapped columns for built-in kinds whose useful fields sit deeper " +
		"than the generic top-level rule reaches. A kind not listed here gets " +
		"only the universal columns plus its own top-level fields.\n\n")
	for _, gvk := range k8s.PromotedKinds() {
		g := gvk.Group
		if g == "" {
			g = "core"
		}
		fmt.Fprintf(w, "### %s (`%s/%s`)\n\n", gvk.Kind, g, gvk.Version)
		colTable(w, k8s.PromotedColumns(gvk))
		w.WriteString("\n")
	}

	w.WriteString("## Top-level fields\n\n" +
		"After the universal and promoted columns, each of the kind's own " +
		"top-level fields becomes a column, in sorted order: `jsonb` for objects " +
		"and arrays, `text` otherwise. Field names are normalised to SQL " +
		"identifiers, so `camelCase` becomes `snake_case`, any character outside " +
		"`[a-z0-9_]` becomes an underscore, runs collapse, and a leading digit is " +
		"prefixed. Two fields that normalise to the same name produce no column " +
		"at all rather than an arbitrary winner.\n\n")
	fmt.Fprintf(w, "These fields never become columns of their own, because a "+
		"universal column already covers them: %s.\n\n", codeList(k8s.SkippedTopLevelFields()))

	w.WriteString("## `raw`\n\n" +
		"Every table ends with a `raw jsonb` column holding the whole object. " +
		"It is reserved before any other name is considered, so a kind with its " +
		"own top-level `raw` field does not displace it. It is also how to read " +
		"anything no column promotes, and how to write a field no column " +
		"exposes.\n")
	return w.Bytes(), nil
}

func colTable(w *bytes.Buffer, cols []k8s.Column) {
	fmt.Fprintf(w, "| Column | Type | Source |\n|---|---|---|\n")
	for _, c := range cols {
		fmt.Fprintf(w, "| `%s` | `%s` | `%s` |\n", c.Name, c.Type, c.Source)
	}
}

func codeList(ss []string) string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	switch len(out) {
	case 0:
		return "none"
	case 1:
		return out[0]
	}
	return strings.Join(out[:len(out)-1], ", ") + " and " + out[len(out)-1]
}
